
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: mydotnetcoreapp
          uri: http://localhost:9091
          predicates:
            - Path=/mydotnetcoreapp/**
          filters:
            - StripPrefix=1
        - id: spring-application
          uri: http://localhost:8080
          predicates:
            - Path=/spring-application/**
          filters:
            - StripPrefix=1
server:
  port: 8585
logging:
  level:
    root: DEBUG